Created model of location, added presence validations and correspondi…
Ichenn92/peruname pull request #3
Opened 2021-02-23 20:49 UTC by michaellaurac

Hello la team,
I just created the model of the location with city and address
Added validation of the presence of both fields
Created two tests to verify the presence of both fields
See you

2021-02-23 22:04 UTC, Ichenn92 commented on app/models/location.rb
> +  validates :city, presence: true
Je sais que tu aimes les one-liner 😄
tu pouvais mettre validates_presence_of.

les 2 vont :)

2021-02-23 22:10 UTC, Ichenn92 commented on test/models/location_test.rb
> +    assert_not test_location.valid?, test_location.errors.full_messages.inspect
il aurait été intéressant d'ajouter le test de validité. 
Quand tu passe les 2 éléments

```ruby
test "presence of city" do
    test_location = @@base_valid_location
    assert test_location.valid?, test_location.errors.full_messages.inspect
end
```

2021-02-23 22:11 UTC, Ichenn92 requested changes
Le premier commentaire est plus pour le fun.
par contre le test de validité serait important de tester. surtout si on décide de faire de l'intégration continu.

Sinon nice & clean

2021-02-24 16:47 UTC, clem13-coder submitted a review, later dismissed

2021-02-25 18:19 UTC, Ichenn92 approved these changes

2021-02-25 18:21 UTC, clem13-coder approved these changes

2021-02-25 18:22 UTC, michaellaurac commented on app/models/location.rb
> +  validates :city, presence: true
Comme vu avec toi, on se donne le choix de faire progresser les validations en gardant chaque champ sur une ligne, par exemple une inclusion dans les villes suisses.

2021-02-25 18:22 UTC, merged