Updated seed with realistic description and prices
Ichenn92/peruname pull request #30
Opened 2021-03-03 22:21 UTC by michaellaurac

Updated seed with realistic description and prices

2021-03-03 22:22 UTC, Ichenn92 approved these changes

2021-03-03 22:51 UTC, Ichenn92 requested changes
Tant que tu es sur la seed, est-ce que tu pourrais mettre les heures de dispo seulement en heure ?
```ruby
availability_start_time: Tod::TimeOfDay.new(8)
availability_end_time: Tod::TimeOfDay.new(19)
```
par exemple.

2021-03-04 17:30 UTC, clem13-coder approved these changes

2021-03-04 19:33 UTC, clem13-coder approved these changes

2021-03-04 19:34 UTC, merged